#Vagrant.configure("2") do |config|
#  config.vm.box = 'centos/7'
#  config.vm.hostname = 'manager'
#  config.vm.network "private_network", ip: "192.168.56.9"
#  config.vm.provider 'virtualbox' do |v|
#    v.memory =2048
#  end
#end

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Config k33 cluster"

  # Definindo a máquina 'manager'
  config.vm.define "manager" do |manager|
    manager.vm.box = 'centos/7'
    manager.vm.hostname = 'manager'
    manager.vm.network "private_network", ip: "192.168.56.9"
    manager.vm.provider 'virtualbox' do |mprovider|
      mprovider.memory = 2048
    end
    manager.vm.network "forwarded_port", guest: 80, host: 80
    manager.vm.network "forwarded_port", guest: 6443, host: 6443
  end

  # Definindo a máquina 'worker1'
  config.vm.define "worker1" do |worker1|
    worker1.vm.box = 'centos/7'
    worker1.vm.hostname = 'worker1'
    worker1.vm.provider 'virtualbox' do |wprovider|
      wprovider.memory = 1024
    end
    worker1.vm.network "private_network", ip: "192.168.56.10"
  end
end
