Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.56.1"
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [".git/"]
  config.vm.provision "shell", path: "provision.sh"
  config.ssh.insert_key = false
end