Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.56.2"
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.provision "shell", path: "provision.sh"
  config.ssh.insert_key = false
end